### ISSUE TITLE
Create a process for a new list.

### ISSUE THREAD

**Issue by caleb-davenport** [caleb-davenport/EECS1510-Project7#6]
Essentially, clear the current list of entries.

**Comment by Roanmh** [comment]
Added Basic functionality. Do we want a confirmation dialog?

**Comment by caleb-davenport** [comment]
I think that would be a good thing to add. It should be a relatively easy dialog box.

**Comment by Roanmh** [comment]
Finished!
![newlistconfirationdialog](https://cloud.githubusercontent.com/assets/10479270/14928260/cacf3408-0e24-11e6-9fc5-84c2e82eb97a.PNG)
